### PR TITLE
Enable zstandard compression for h5py by default

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by dneise** [comment]
Is there also a test for travis, which tests writing with zstandard? If I understand the test correctly, it tests for writing without compression only, right?

**Comment by maxnoe** [comment]
> Is there also a test for travis, which tests writing with zstandard? If I understand the test correctly, it tests for writing without compression only, right?

As compression is now on by default, every test besides the no compression test should be testing the compression (and this is also what fails at the moment on travis)

**Comment by maxnoe** [comment]
I have also problems getting this to run in a non-conda environment on my local machine.

**Comment by dneise** [comment]
ah .. I missed entirely, that this is not running on travis

**Review by dneise — APPROVED** [review]

**Comment by maxnoe** [comment]
Ok, the solution was that h5py and pytables must be linked vs the same libhdf5 for this to work.
The pypi wheels bring their own, so it only works with conda or when you build the wheel yourself against a system libhdf5

**Pull request merged**
