### PR TITLE
introduce some more numbers needed by `photon_stream` repo

### PR DESCRIPTION
**Pull request by dneise**
Hello :-D

I need these numbers in the "photon_stream" repo
this is not changing the existing API, so should be harmless.

### CODE REVIEW

**Comment by dneise** [comment]
Oh sorry ... I just see .. .it does change the API ... fixing it ... just a minute

**Comment by dneise** [comment]
I would like travis to upload this new version 0.8.4 immediately to pypi as soon as we merged this into the master. I know I have to add a new tag for this. 

Can I add a tag to this branch already now and as soon as the branch is merged, all is fine?

**Comment by maxnoe** [comment]
No, the tag should be created once this is merged into master and the tag should point to the merge commit.

**Comment by dneise** [comment]
okay thanks

**Review by maxnoe — APPROVED** [review]

**Pull request merged**
