### PR TITLE
Adapt to peewee > 3

### PR DESCRIPTION
**Pull request by maxnoe**
This adapts the breaking changes in peewee 3.0 (current version is 3.7)

### CODE REVIEW

**Comment by dneise** [comment]
Awesome, did you make the  `models.py` with pwiz? So we do not have to review it? Or did you make it somehow by hand?

**Review by dneise — APPROVED** [review]
Looks good to me, did not read every diff in `models.py` though

**Comment by maxnoe** [comment]
> Awesome, did you make the models.py with pwiz? So we do not have to review it? Or did you make it somehow by hand?

I used the peewee tool to generate models from a database connection. 
I know just used search and replace to adapt to the changes in peewee 3

**Comment by dneise** [comment]
Ah right ... search and replace should be fine

**Pull request merged**
